version: '3.1'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: joomlatools/console
    networks:
      - appnet
    ports:
      - 8085:80
    volumes:
      - ./:/joomlatools
  db:
    image: mysql:5.6
    networks:
      - appnet
    ports:
      - 8086:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    logging:
      driver: none

networks:
  appnet:
    driver: bridge
